[package]
name = "tiny-rng"
version = "0.2.0"
edition = "2018"
authors = ["Finn <finn.bcd@gmail.com>"]
license = "CC0-1.0"

description = "Tiny RNG, a minimal random number generator"
repository = "https://github.com/JohnBSmith/tiny-rng"
readme = "README.md"

